### ISSUE TITLE
Modern unix-tool replacements?

### ISSUE THREAD

**Issue by SKyletoft** [toasterbag/data101#6]
ls → exa/lsd
diff → difftastic
and so on

**Comment by toasterbag** [comment]
Thanks for your suggestion!
After some discussion we came to the conclusion that, while these are great tools, they come with some obstacles that make this topic unsuitable for Data101 in its current format.

To be more precise: This would be a significant amount of content, as we would want to explain the differences and why these are worth it. We also do not believe that our target audience is quite right for this topic. If however, Data101 grows to cover more content we may wish to reconsider this suggestion!
